import { useState, useEffect } from 'react';
import { PageHeader } from '@/components/crud/PageHeader';
import { DataTable } from '@/components/crud/DataTable';
import { SearchFilter } from '@/components/crud/SearchFilter';
import { Pagination } from '@/components/crud/Pagination';
import { CRUDModal } from '@/components/crud/CRUDModal';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { reportService, schoolService } from '@/services/dataService';
import type { Report } from '@/types';
import { toast } from 'sonner';
import {
  Users,
  Calendar,
  TrendingUp,
  FileSpreadsheet,
  PieChart,
} from 'lucide-react';

export function Reports() {
  const [reports, setReports] = useState<Report[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [loading, setLoading] = useState(false);

  const [schools, setSchools] = useState<{ id: string; name: string }[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const [formData, setFormData] = useState<Partial<Report>>({
    name: '',
    type: 'enrollment',
    description: '',
    filters: {},
  });

  useEffect(() => {
    const allSchools = schoolService.getAll({ limit: 100 });
    setSchools(allSchools.data.map(s => ({ id: s.id, name: s.name })));
  }, []);

  const fetchReports = () => {
    setLoading(true);
    const result = reportService.getAll({
      page,
      limit,
      search,
    });
    setReports(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  useEffect(() => {
    fetchReports();
  }, [page, limit, search, typeFilter]);

  const handleGenerateReport = () => {
    try {
      reportService.create({
        ...formData,
        name: formData.name || '',
        type: formData.type || 'custom',
        filters: formData.filters || {},
        generatedBy: '1',
        generatedAt: new Date().toISOString(),
        status: 'pending',
      });
      toast.success('Report generation started');
      setIsModalOpen(false);
      fetchReports();
    } catch (error) {
      toast.error('Something went wrong');
    }
  };

  const clearFilters = () => {
    setSearch('');
    setTypeFilter('');
    setPage(1);
  };

  const reportTypes = [
    { type: 'enrollment', label: 'Enrollment Report', icon: Users, color: 'bg-blue-500/10 text-blue-500' },
    { type: 'attendance', label: 'Attendance Report', icon: Calendar, color: 'bg-emerald-500/10 text-emerald-500' },
    { type: 'grades', label: 'Grades Report', icon: TrendingUp, color: 'bg-amber-500/10 text-amber-500' },
    { type: 'financial', label: 'Financial Report', icon: FileSpreadsheet, color: 'bg-purple-500/10 text-purple-500' },
    { type: 'custom', label: 'Custom Report', icon: PieChart, color: 'bg-rose-500/10 text-rose-500' },
  ];

  const columns = [
    { key: 'name', header: 'Report Name' },
    { key: 'type', header: 'Type', width: '120px', render: (item: Report) => (
      <span className="capitalize">{item.type}</span>
    )},
    { key: 'description', header: 'Description' },
    { key: 'generatedByName', header: 'Generated By' },
    { key: 'generatedAt', header: 'Generated At', width: '150px' },
    { key: 'status', header: 'Status', width: '100px' },
  ];

  return (
    <div className="space-y-4">
      <PageHeader
        title="Reports & Analytics"
        description="Generate and view comprehensive reports"
        onAdd={() => setIsModalOpen(true)}
        addButtonLabel="Generate Report"
      />

      {/* Quick Report Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        {reportTypes.map((reportType) => {
          const Icon = reportType.icon;
          return (
            <Card
              key={reportType.type}
              className="cursor-pointer hover:shadow-lg transition-all duration-300 rounded-2xl border-border/50"
              onClick={() => {
                setFormData({ ...formData, type: reportType.type as any });
                setIsModalOpen(true);
              }}
            >
              <CardContent className="p-4">
                <div className={`w-10 h-10 rounded-xl ${reportType.color} flex items-center justify-center mb-3`}>
                  <Icon className="h-5 w-5" />
                </div>
                <p className="text-sm font-medium">{reportType.label}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <SearchFilter
          searchValue={search}
          onSearchChange={setSearch}
          searchPlaceholder="Search reports..."
          filters={[
            {
              key: 'type',
              label: 'Type',
              options: reportTypes.map(r => ({ value: r.type, label: r.label })),
              value: typeFilter,
              onChange: setTypeFilter,
            },
          ]}
          onClearFilters={clearFilters}
          showClearButton={true}
        />
      </div>

      <DataTable
        data={reports}
        columns={columns}
        onView={(item) => toast.info(`Viewing report: ${item.name}`)}
        loading={loading}
        emptyMessage="No reports found"
      />

      <Pagination
        currentPage={page}
        totalPages={Math.ceil(total / limit)}
        totalItems={total}
        itemsPerPage={limit}
        onPageChange={setPage}
        onItemsPerPageChange={setLimit}
      />

      <CRUDModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Report"
        mode="create"
        onSubmit={handleGenerateReport}
        submitLabel="Generate"
      >
        <div className="grid gap-4">
          <div className="space-y-2">
            <Label htmlFor="reportName">Report Name *</Label>
            <Input
              id="reportName"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="Enter report name"
              className="rounded-xl"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="reportType">Report Type *</Label>
            <Select
              value={formData.type}
              onValueChange={(value: any) => setFormData({ ...formData, type: value })}
            >
              <SelectTrigger className="rounded-xl">
                <SelectValue placeholder="Select report type" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                {reportTypes.map((type) => (
                  <SelectItem key={type.type} value={type.type} className="rounded-lg">
                    {type.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Input
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Enter description (optional)"
              className="rounded-xl"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="schoolFilter">School Filter</Label>
            <Select
              value={formData.filters?.schoolId || ''}
              onValueChange={(value) => setFormData({
                ...formData,
                filters: { ...formData.filters, schoolId: value }
              })}
            >
              <SelectTrigger className="rounded-xl">
                <SelectValue placeholder="All Schools" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                <SelectItem value="" className="rounded-lg">All Schools</SelectItem>
                {schools.map((school) => (
                  <SelectItem key={school.id} value={school.id} className="rounded-lg">
                    {school.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={formData.filters?.startDate || ''}
                onChange={(e) => setFormData({
                  ...formData,
                  filters: { ...formData.filters, startDate: e.target.value }
                })}
                className="rounded-xl"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={formData.filters?.endDate || ''}
                onChange={(e) => setFormData({
                  ...formData,
                  filters: { ...formData.filters, endDate: e.target.value }
                })}
                className="rounded-xl"
              />
            </div>
          </div>
        </div>
      </CRUDModal>
    </div>
  );
}
